language: ruby 
rvm:
  - 2.3.1
env:
  - DB=SQLite
script:
 - bundle install
 - RAILS_ENV=test bundle exec rake db:migrate --trace
 - bundle exec rake db:test:prepare
deploy:
  provider: pages
  skip-cleanup: true
   github-token: paULPzERaxGkpByzq9TFqP5L40uSOMLWeCibBRF9eqF5iACpxbIdVcazHA0MetFdGzMAOMwlDF87Rg9e+XoFDMZiC3zq7RW7DQ+wBxueiRBqQn/GrkLdX7wBvxOA81JnY/nSD9GinI6N8qSsO87Tmo7okhn/PcTLikawkH6i39NIga53xol9ohNrzWuFAH3ae0AHpDkcF+M/lvAgOM3d65hkYcLMrPuGkPAU1tuMVYcUf6h5m8GZpIDpROmU4I4Ylx8YmT718C/6VV+3old5e4Qobmuaw5bYeGuko+/3lPZ+GMLZr0o2gSSXi3FVwXZLmZ7aZpd5VjIFg2SzSt2v2ncZDeMk0uN6aYE7FLnvXI/u+3gcM5m+diE5LLsR+1agaKFMbQICe39uFgFQrBVG7PPvzMI9xVG7VpGyJKLajiqmtRtUD76R1AWxzWch3ZkkSRa79sG0lHizbOvO3jkZ1Xf7ZVMkcy3geRCBH/tfDAVQWIyFOWL5vGuVORVa0I5JG2Gh8fhA1LJMMCQoTQ8u3wUUMByGuzWhxfSyYHzBi91OJem3u38XAYjsHTpp/uYkh/2BubNcG/Nzo7Em9M0SULr9EW3Eixbgm5hsxZbcDyLCGqAUIbYZW8DRnIx1p0hhfDY2xKhtWdG4DCUbaLtLxjuqZxDDAFVoyYyan/xgVeM=
  keep-history: true
  on:
    branch: master
